apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: db
spec:
  containers:
  - name: db
    image: postgres
    env:
      - name: POSTGRES_PASSWORD
        value: "postgres"
      - name: POSTGRES_USER
        value: "postgres"
    ports:
      - containerPort: 5432