apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
spec:
  replicas: 2
  selector:
    matchLabels:
      name: voting
  template:
    metadata:
      labels:
        name: voting
    spec:
      containers:
      - name: voting
        image: kodekloud/examplevotingapp_vote:v1
        ports:
          - containerPort: 80
