apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
      - name: myapp
        image: hamzanaser/api:latest
        # image: nginx
        resources:
          limits:
            memory: "64Mi"
            cpu: "300m"
