apiVersion: v1
kind: Service
metadata:
  name: service-port
spec:
  type: NodePort
  selector:
    name: myapp
  ports:
  - nodePort: 30000 # 30000 - 32767
    port: 80  # Service Port
    targetPort: 5000
    


