apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replica
  labels:
    app: my-replica
    type: front-end
spec:
  replicas: 3
  # selector:
  #   app: my-replica

  template:
    metadata:
      name: my-api
      labels:
        name: myapp
    spec:
      containers:
      - name: my-api
        image: hamzanaser/api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 5000


